version: "3.8"
services:
  dbTienda:
    container_name: bdTienda
    image: postgres:14.3
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASS: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  webtiendanest:
    container_name: apiTienda
    image: apitiendanest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - PROYECTO=${PROYECTO}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_PORT=${DB_PORT}
        - NEST_PORT=${NEST_PORT}
    env_file:
       - ./.env
    ports:
      - ${NEST_PORT}:80
    volumes:
      - ./web:/var/www/html
      - ./logs:/var/logs
    # depends_on:
    #   - db  