# version: "3.8"
# services:
#   dbtienda:
#     container_name: bdpostgre
#     image: postgres:14.3
#     restart: always
#     ports:
#       - ${DB_PORT}:5432
#     environment:
#       POSTGRES_PASSWORD: ${DB_PASS}
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
  
version: '3'
services:
  dbpostgres:
    image: postgres:14.3
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: dbtienda
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks: 
       net_api_tienda:
           ipv4_address: ${DB_HOST}

  webtiendaback:
    container_name: apitienda
    image: apitienda
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROYECTO=${PROYECTO}
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_PORT=${DB_PORT}
        - NEST_PORT=${NEST_PORT}
    env_file:
       - ./.env
    ports:
      - ${NEST_PORT}:3000
    volumes:
      - .:/usr/src/app
networks: 
  net_api_tienda:
    ipam: 
      driver: default
      config: 
        - subnet: ${DB_NETWORK}