version: '3.8'
services:
  api:
    build: .
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}  
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      NODE_ENV: ${NODE_ENV}
    env_file:
      - .env
    ports:
      - ${NEST_PORT}:3000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
  nginx:
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - ${WWW_PORT}:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf